### ISSUE TITLE
Date issue in iOS

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/mobile-app#108]
Date issue in iOS with latest version of frappe.

![image](https://user-images.githubusercontent.com/973676/139103784-f2ec9bb2-cdc9-42f6-a2e4-65bd84b1c221.png)
![image](https://user-images.githubusercontent.com/973676/139103797-688cd840-4a93-4396-8899-87e97f6cddc2.png)
![image](https://user-images.githubusercontent.com/973676/139103810-dcc772f1-3f89-4b21-a9c5-8d952e01d28d.png)

**Comment by sumitbhanushali** [comment]
fix for this has just been released, can you check and confirm?

**Comment by mohsinalimat** [comment]
In Today release version issue solve.
